language: python
python:
  - "2.7"
env:
  - DISPLAY=:99.0
before_install:
  - sh -e /etc/init.d/xvfb start
# dependencies
install:
  - pip install pyglet configparser
# run tests
script:
  - python fightstick.py
