language: python
sudo: true
python:
  - "2.7"
  - "3.5"
env:
  - DISPLAY=:99.0
before_install:
  - sh -e /etc/init.d/xvfb start
  - sudo touch /dev/input/js0
# dependencies
install:
  - pip install pyglet configparser pytest
# run tests
script:
  - pytest
