language: python
sudo: true
python:
  - "3.7"
env:
  - DISPLAY=:99.0
before_install:
  - sh -e /etc/init.d/xvfb start
  - sudo touch /dev/input/js0
# dependencies
install:
  - pip install pyglet configparser
# run tests
script:
  - python3 fightstick.py &disown
