# appveyor.yml - https://www.appveyor.com/docs/lang/python
---
image:
  - Visual Studio 2019

environment:
  matrix:
  - TOXENV: py37
  - TOXENV: py38
  - TOXENV: py39
  - TOXENV: py310

build: false

install:
  # - py --list
  # - py -m pip install --upgrade pip
  - py -m pip install tox pyglet configparser

test_script:
  - py -m python3 fightstick.py &disown
