__author__ = 'Benjamin Moran'

from pyglet import compat_platform


# def get_guid(device):
#     """Generate a Game Controller GUID from a joystick device.
#
#     :param device: a pyglet joystick device
#     :return: SDL2 format Game Controller GUID
#
#     """
#     if compat_platform.startswith("linux"):
#         bustype_hex = format(device.id_bustype, "02x")[-2:]
#         bustype_shifted = str(device.id_bustype >> 8)[-2:]
#         vendor_hex = format(int(device.id_vendor, 16), "02x")[-2:]
#         vendor_shifted = str(int(device.id_vendor, 16) >> 8)[-2:]
#         product_hex = format(int(device.id_product, 16), "02x")[-2:]
#         product_shifted = str(int(device.id_product, 16) >> 8)[-2:]
#         version_hex = format(device.id_version, "02x")[-2:]
#         version_shifted = str(device.id_version >> 8)[-2:]
#         # An empty string with formatted slots that will become the final guid:
#         slug = "{:0>2}{:0>2}0000{:0>2}{:0>2}0000{:0>2}{:0>2}0000{:0>2}{:0>2}0000"
#         return slug.format(bustype_hex, bustype_shifted, vendor_hex,
#                            vendor_shifted, product_hex, product_shifted,
#                            version_hex, version_shifted)
#     elif compat_platform.startswith("win"):
#         # Add missing leading 0s in the hex string, if necessary:
#         di_guid = device.id_product_guid
#
#         # The GUID must be reversed, in 2-bit chunks:
#         swapped_guid = di_guid[6:8] + di_guid[4:6] + di_guid[2:4] + di_guid[0:2]
#
#         # An empty string with formatted slots that will become the final guid:
#         slug = "{}000000000000504944564944"
#         return slug.format(swapped_guid)
#     elif compat_platform.startswith("darwin"):
#         raise NotImplementedError


def add_mappings_from_file(filename, file=None):
    """Add additional Game Controller mappings to the internal database.

    :Parameters:
        `filename` : str
            The filename of the text file containing the mappings.
    """
    if not file:
        file = open(filename)

    try:
        new_mappings = _parse_raw_mappings(file.read())
        for mapping in new_mappings:
            if not any(mapping["guid"] == m["guid"] for m in mapping_list):
                mapping_list.append(mapping)
    finally:
        file.close()


# TODO: handle the new "+" and "-" prefixes for axis.
def _parse_raw_mappings(rawstring):
    """Parse a string of raw SDL2 mappings, and return mapping dicts.

    :param rawstring: A string containing the raw mappings
    :return: A list of mapping dicts.
    """

    def _map_pair(raw_relation):
        relation = raw_relation.split(":")[1]
        if relation.startswith("b"):
            return "button", int(relation[1:])
        elif relation.startswith("a"):
            return "axis", int(relation[1:])
        elif relation.startswith("h0"):
            return "hat0", int(relation.split(".")[1])

    parsed_mappings = []

    for line in rawstring.splitlines():
        line = line.strip()
        if line.startswith("#"):  # Skip commented lines.
            continue
        if not line.strip():  # Skip empty lines.
            continue
        raw_mapping = line.split(",")

        mapping = dict(guid=None, name=None, guide=None, a=None, b=None,
                       x=None, y=None, leftshoulder=None, leftstick=None,
                       rightshoulder=None, rightstick=None, back=None,
                       start=None, dpup=None, dpdown=None, dpleft=None,
                       dpright=None, lefttrigger=None, righttrigger=None,
                       leftx=None, lefty=None, rightx=None, righty=None)
        mapping["guid"] = raw_mapping[0]
        mapping["name"] = raw_mapping[1]

        for item in raw_mapping:
            if item.startswith("guide:"):
                mapping["guide"] = _map_pair(item)
            elif item.startswith("a:"):
                mapping["a"] = _map_pair(item)
            elif item.startswith("b:"):
                mapping["b"] = _map_pair(item)
            elif item.startswith("x:"):
                mapping["x"] = _map_pair(item)
            elif item.startswith("y:"):
                mapping["y"] = _map_pair(item)
            elif item.startswith("leftshoulder:"):
                mapping["leftshoulder"] = _map_pair(item)
            elif item.startswith("leftstick:"):
                mapping["leftstick"] = _map_pair(item)
            elif item.startswith("rightshoulder:"):
                mapping["rightshoulder"] = _map_pair(item)
            elif item.startswith("rightstick:"):
                mapping["rightstick"] = _map_pair(item)
            elif item.startswith("back:"):
                mapping["back"] = _map_pair(item)
            elif item.startswith("start:"):
                mapping["start"] = _map_pair(item)
            elif item.startswith("lefttrigger:"):
                mapping["lefttrigger"] = _map_pair(item)
            elif item.startswith("righttrigger:"):
                mapping["righttrigger"] = _map_pair(item)
            elif item.startswith("dpup"):
                mapping["dpup"] = _map_pair(item)
            elif item.startswith("dpdown"):
                mapping["dpdown"] = _map_pair(item)
            elif item.startswith("dpleft"):
                mapping["dpleft"] = _map_pair(item)
            elif item.startswith("dpright"):
                mapping["dpright"] = _map_pair(item)
            elif item.startswith("leftx"):
                mapping["leftx"] = _map_pair(item)
            elif item.startswith("lefty"):
                mapping["lefty"] = _map_pair(item)
            elif item.startswith("rightx"):
                mapping["rightx"] = _map_pair(item)
            elif item.startswith("righty"):
                mapping["righty"] = _map_pair(item)
            elif item.startswith("platform:"):
                mapping["platform"] = item.split(":")[1]

        parsed_mappings.append(mapping)

    return parsed_mappings


def is_game_controller(device):
    """Check if the passed joystick device is a Game Controller.

    :param device: a pyglet joystick device
    :return True if this joystick is a Game Controller.
    """
    return any(device.get_guid() == m["guid"] for m in mapping_list)


def get_mapping(guid):
    """Return a mapping for the passed device GUID.

    :param guid: The game controller's GUID.
    :return The Game Controller axis and button mappings.
    """
    for mapping in mapping_list:
        if mapping["guid"] == guid:
            return mapping


def _get_map(mapping, relation):
    if relation in mapping.keys():
        return mapping[relation]
    else:
        return None


if compat_platform.startswith("linux"):
    mapping_list = [
        {'lefttrigger': None, 'leftshoulder': ('button', 6), 'dpup': None, 'dpdown': None,
         'dpleft': None, 'dpright': None, 'platform': 'Linux', 'y': ('button', 3), 'guide': None,
         'name': 'NES30 wired', 'lefty': ('axis', 1), 'start': ('button', 11),
         'righttrigger': None, 'rightx': None, 'x': ('button', 4), 'back': ('button', 10),
         'righty': None, 'a': ('button', 1), 'b': ('button', 0), 'leftx': ('axis', 0),
         'rightstick': None, 'leftstick': None, 'rightshoulder': ('button', 7),
         'guid': '030000003512000012ab000010010000'},
        {'lefttrigger': ('button', 6), 'leftshoulder': ('button', 4), 'dpright': ('hat0', 2),
         'platform': 'Linux', 'y': ('button', 3), 'guide': None, 'name': 'GameStop Gamepad',
         'lefty': ('axis', 1), 'start': ('button', 9), 'righttrigger': ('button', 7),
         'rightx': ('axis', 2), 'x': ('button', 2), 'dpdown': ('hat0', 4), 'dpleft': ('hat0', 8),
         'back': ('button', 8), 'dpup': ('hat0', 1), 'righty': ('axis', 3), 'a': ('button', 0),
         'b': ('button', 1), 'leftx': ('axis', 0), 'rightstick': ('button', 11),
         'leftstick': ('button', 10), 'rightshoulder': ('button', 5),
         'guid': '0500000047532047616d657061640000'},
        {'lefttrigger': ('button', 6), 'leftshoulder': ('button', 4), 'dpright': ('hat0', 2),
         'platform': 'Linux', 'y': ('button', 0), 'guide': None,
         'name': 'Jess Technology USB Game Controller', 'lefty': ('axis', 1),
         'start': ('button', 9), 'righttrigger': ('button', 7), 'rightx': ('axis', 3),
         'x': ('button', 3), 'dpdown': ('hat0', 4), 'dpleft': ('hat0', 8), 'back': ('button', 8),
         'dpup': ('hat0', 1), 'righty': ('axis', 2), 'a': ('button', 2), 'b': ('button', 1),
         'leftx': ('axis', 0), 'rightstick': None, 'leftstick': None,
         'rightshoulder': ('button', 5), 'guid': '03000000ba2200002010000001010000'},
        {'lefttrigger': ('button', 6), 'leftshoulder': ('button', 4), 'dpright': ('hat0', 2),
         'platform': 'Linux', 'y': ('button', 3), 'guide': None,
         'name': 'Logitech Cordless RumblePad 2', 'lefty': ('axis', 1), 'start': ('button', 9),
         'righttrigger': ('button', 7), 'rightx': ('axis', 2), 'x': ('button', 0),
         'dpdown': ('hat0', 4), 'dpleft': ('hat0', 8), 'back': ('button', 8), 'dpup': ('hat0', 1),
         'righty': ('axis', 3), 'a': ('button', 1), 'b': ('button', 2), 'leftx': ('axis', 0),
         'rightstick': ('button', 11), 'leftstick': ('button', 10), 'rightshoulder': ('button', 5),
         'guid': '030000006d04000019c2000010010000'},
        {'lefttrigger': ('axis', 2), 'leftshoulder': ('button', 4), 'dpright': ('hat0', 2),
         'platform': 'Linux', 'y': ('button', 3), 'guide': ('button', 8),
         'name': 'Logitech F310 Gamepad (XInput)', 'lefty': ('axis', 1), 'start': ('button', 7),
         'righttrigger': ('axis', 5), 'rightx': ('axis', 3), 'x': ('button', 2),
         'dpdown': ('hat0', 4), 'dpleft': ('hat0', 8), 'back': ('button', 6), 'dpup': ('hat0', 1),
         'righty': ('axis', 4), 'a': ('button', 0), 'b': ('button', 1), 'leftx': ('axis', 0),
         'rightstick': ('button', 10), 'leftstick': ('button', 9), 'rightshoulder': ('button', 5),
         'guid': '030000006d0400001dc2000014400000'},
        {'lefttrigger': ('axis', 2), 'leftshoulder': ('button', 4), 'dpright': ('hat0', 2),
         'platform': 'Linux', 'y': ('button', 3), 'guide': ('button', 8),
         'name': 'Logitech F510 Gamepad (XInput)', 'lefty': ('axis', 1), 'start': ('button', 7),
         'righttrigger': ('axis', 5), 'rightx': ('axis', 3), 'x': ('button', 2),
         'dpdown': ('hat0', 4), 'dpleft': ('hat0', 8), 'back': ('button', 6), 'dpup': ('hat0', 1),
         'righty': ('axis', 4), 'a': ('button', 0), 'b': ('button', 1), 'leftx': ('axis', 0),
         'rightstick': ('button', 10), 'leftstick': ('button', 9), 'rightshoulder': ('button', 5),
         'guid': '030000006d0400001ec2000020200000'},
        {'lefttrigger': ('button', 6), 'leftshoulder': ('button', 4), 'dpright': ('hat0', 2),
         'platform': 'Linux', 'y': ('button', 3), 'guide': None,
         'name': 'Logitech F710 Gamepad (DInput)', 'lefty': ('axis', 1), 'start': ('button', 9),
         'righttrigger': ('button', 7), 'rightx': ('axis', 2), 'x': ('button', 0),
         'dpdown': ('hat0', 4), 'dpleft': ('hat0', 8), 'back': ('button', 8), 'dpup': ('hat0', 1),
         'righty': ('axis', 3), 'a': ('button', 1), 'b': ('button', 2), 'leftx': ('axis', 0),
         'rightstick': ('button', 11), 'leftstick': ('button', 10), 'rightshoulder': ('button', 5),
         'guid': '030000006d04000019c2000011010000'},
        {'lefttrigger': ('axis', 2), 'leftshoulder': ('button', 4), 'dpright': ('hat0', 2),
         'platform': 'Linux', 'y': ('button', 3), 'guide': ('button', 8),
         'name': 'Logitech F710 Gamepad (XInput)', 'lefty': ('axis', 1), 'start': ('button', 7),
         'righttrigger': ('axis', 5), 'rightx': ('axis', 3), 'x': ('button', 2),
         'dpdown': ('hat0', 4), 'dpleft': ('hat0', 8), 'back': ('button', 6), 'dpup': ('hat0', 1),
         'righty': ('axis', 4), 'a': ('button', 0), 'b': ('button', 1), 'leftx': ('axis', 0),
         'rightstick': ('button', 10), 'leftstick': ('button', 9), 'rightshoulder': ('button', 5),
         'guid': '030000006d0400001fc2000005030000'},
        {'lefttrigger': ('button', 8), 'leftshoulder': ('button', 10), 'dpright': ('button', 5),
         'platform': 'Linux', 'y': ('button', 12), 'guide': ('button', 16),
         'name': 'PS3 Controller', 'lefty': ('axis', 1), 'start': ('button', 3),
         'righttrigger': ('button', 9), 'rightx': ('axis', 2), 'x': ('button', 15),
         'dpdown': ('button', 6), 'dpleft': ('button', 7), 'back': ('button', 0),
         'dpup': ('button', 4), 'righty': ('axis', 3), 'a': ('button', 14), 'b': ('button', 13),
         'leftx': ('axis', 0), 'rightstick': ('button', 2), 'leftstick': ('button', 1),
         'rightshoulder': ('button', 11), 'guid': '030000004c0500006802000011010000'},
        {'lefttrigger': ('axis', 3), 'leftshoulder': ('button', 4), 'dpright': ('hat0', 2),
         'platform': 'Linux', 'y': ('button', 3), 'guide': ('button', 12),
         'name': 'Sony DualShock 4', 'lefty': ('axis', 1), 'start': ('button', 9),
         'righttrigger': ('axis', 4), 'rightx': ('axis', 2), 'x': ('button', 0),
         'dpdown': ('hat0', 4), 'dpleft': ('hat0', 8), 'back': ('button', 8), 'dpup': ('hat0', 1),
         'righty': ('axis', 5), 'a': ('button', 1), 'b': ('button', 2), 'leftx': ('axis', 0),
         'rightstick': ('button', 11), 'leftstick': ('button', 10), 'rightshoulder': ('button', 5),
         'guid': '030000004c050000c405000011010000'},
        {'lefttrigger': ('button', 6), 'leftshoulder': ('button', 4), 'dpright': ('hat0', 2),
         'platform': 'Linux', 'y': ('button', 3), 'guide': ('button', 12),
         'name': 'EA Sports PS3 Controller', 'lefty': ('axis', 1), 'start': ('button', 9),
         'righttrigger': ('button', 7), 'rightx': ('axis', 2), 'x': ('button', 0),
         'dpdown': ('hat0', 4), 'dpleft': ('hat0', 8), 'back': ('button', 8), 'dpup': ('hat0', 1),
         'righty': ('axis', 3), 'a': ('button', 1), 'b': ('button', 2), 'leftx': ('axis', 0),
         'rightstick': ('button', 11), 'leftstick': ('button', 10), 'rightshoulder': ('button', 5),
         'guid': '030000006f0e00003001000001010000'},
        {'lefttrigger': ('axis', 2), 'leftshoulder': ('button', 4), 'dpright': ('hat0', 2),
         'platform': 'Linux', 'y': ('button', 3), 'guide': ('button', 8),
         'name': 'Valve Streaming Gamepad', 'lefty': ('axis', 1), 'start': ('button', 7),
         'righttrigger': ('axis', 5), 'rightx': ('axis', 3), 'x': ('button', 2),
         'dpdown': ('hat0', 4), 'dpleft': ('hat0', 8), 'back': ('button', 6), 'dpup': ('hat0', 1),
         'righty': ('axis', 4), 'a': ('button', 0), 'b': ('button', 1), 'leftx': ('axis', 0),
         'rightstick': ('button', 10), 'leftstick': ('button', 9), 'rightshoulder': ('button', 5),
         'guid': '03000000de280000ff11000001000000'},
        {'lefttrigger': ('axis', 5), 'leftshoulder': ('button', 2), 'dpright': ('hat0', 2),
         'platform': 'Linux', 'y': ('button', 5), 'guide': ('button', 8),
         'name': 'X360 Controller', 'lefty': ('axis', 1), 'start': ('button', 7),
         'righttrigger': ('axis', 2), 'rightx': ('axis', 3), 'x': ('button', 4),
         'dpdown': ('hat0', 4), 'dpleft': ('hat0', 8), 'back': ('button', 6), 'dpup': ('hat0', 1),
         'righty': ('axis', 4), 'a': ('button', 0), 'b': ('button', 1), 'leftx': ('axis', 0),
         'rightstick': ('button', 10), 'leftstick': ('button', 9), 'rightshoulder': ('button', 3),
         'guid': '030000005e0400008e02000014010000'},
        {'lefttrigger': ('axis', 2), 'leftshoulder': ('button', 4), 'dpright': ('hat0', 2),
         'platform': 'Linux', 'y': ('button', 3), 'guide': ('button', 8),
         'name': 'X360 Controller', 'lefty': ('axis', 1), 'start': ('button', 7),
         'righttrigger': ('axis', 5), 'rightx': ('axis', 3), 'x': ('button', 2),
         'dpdown': ('hat0', 4), 'dpleft': ('hat0', 8), 'back': ('button', 6), 'dpup': ('hat0', 1),
         'righty': ('axis', 4), 'a': ('button', 0), 'b': ('button', 1), 'leftx': ('axis', 0),
         'rightstick': ('button', 10), 'leftstick': ('button', 9), 'rightshoulder': ('button', 5),
         'guid': '030000005e0400008e02000010010000'},
        {'lefttrigger': ('axis', 2), 'leftshoulder': ('button', 2), 'dpright': ('hat0', 2),
         'platform': 'Linux', 'y': ('button', 5), 'guide': ('button', 8),
         'name': 'PDP RockCandy X360 Controller', 'lefty': ('axis', 1), 'start': ('button', 7),
         'righttrigger': ('axis', 5), 'rightx': ('axis', 3), 'x': ('button', 4),
         'dpdown': ('hat0', 4), 'dpleft': ('hat0', 8), 'back': ('button', 6), 'dpup': ('hat0', 1),
         'righty': ('axis', 4), 'a': ('button', 0), 'b': ('button', 1), 'leftx': ('axis', 0),
         'rightstick': ('button', 10), 'leftstick': ('button', 9), 'rightshoulder': ('button', 3),
         'guid': '030000006f0e00001f01000000010000'},
        {'lefttrigger': ('axis', 2), 'leftshoulder': ('button', 4), 'dpright': ('button', 12),
         'platform': 'Linux', 'y': ('button', 3), 'guide': ('button', 8),
         'name': 'X360 Wireless Controller', 'lefty': ('axis', 1), 'start': ('button', 7),
         'righttrigger': ('axis', 5), 'rightx': ('axis', 3), 'x': ('button', 2),
         'dpdown': ('button', 14), 'dpleft': ('button', 11), 'back': ('button', 6),
         'dpup': ('button', 13), 'righty': ('axis', 4), 'a': ('button', 0), 'b': ('button', 1),
         'leftx': ('axis', 0), 'rightstick': ('button', 10), 'leftstick': ('button', 9),
         'rightshoulder': ('button', 5), 'guid': '030000005e0400001907000000010000'},
        {'lefttrigger': ('axis', 2), 'leftshoulder': ('button', 4), 'dpright': ('button', 12),
         'platform': 'Linux', 'y': ('button', 3), 'guide': ('button', 8),
         'name': 'Xbox 360 Wireless Receiver', 'lefty': ('axis', 1), 'start': ('button', 7),
         'righttrigger': ('axis', 5), 'rightx': ('axis', 3), 'x': ('button', 2),
         'dpdown': ('button', 14), 'dpleft': ('button', 11), 'back': ('button', 6),
         'dpup': ('button', 13), 'righty': ('axis', 4), 'a': ('button', 0), 'b': ('button', 1),
         'leftx': ('axis', 0), 'rightstick': ('button', 10), 'leftstick': ('button', 9),
         'rightshoulder': ('button', 5), 'guid': '030000005e040000a102000000010000'},
        {'guid': '03000000022000000090000011010000', 'name': '8Bitdo NES30 Pro', 'guide': None,
         'a': ('button', 1), 'b': ('button', 0), 'x': ('button', 4), 'y': ('button', 3),
         'leftshoulder': ('button', 6), 'leftstick': ('button', 13),
         'rightshoulder': ('button', 7), 'rightstick': ('button', 14), 'back': ('button', 10),
         'start': ('button', 11), 'dpup': ('hat0', 1), 'dpdown': ('hat0', 4),
         'dpleft': ('hat0', 8), 'dpright': ('hat0', 2), 'lefttrigger': ('button', 8),
         'righttrigger': ('button', 9), 'leftx': ('axis', 0), 'lefty': ('axis', 1),
         'rightx': ('axis', 2), 'righty': ('axis', 3)},
        {'guid': '05000000203800000900000000010000', 'name': '8Bitdo NES30 Pro', 'guide': None,
         'a': ('button', 1), 'b': ('button', 0), 'x': ('button', 4), 'y': ('button', 3),
         'leftshoulder': ('button', 6), 'leftstick': ('button', 13),
         'rightshoulder': ('button', 7), 'rightstick': ('button', 14), 'back': ('button', 10),
         'start': ('button', 11), 'dpup': ('hat0', 1), 'dpdown': ('hat0', 4),
         'dpleft': ('hat0', 8), 'dpright': ('hat0', 2), 'lefttrigger': ('button', 8),
         'righttrigger': ('button', 9), 'leftx': ('axis', 0), 'lefty': ('axis', 1),
         'rightx': ('axis', 2), 'righty': ('axis', 3)},
        {'guid': '05000000102800000900000000010000', 'name': '8Bitdo SFC30 GamePad', 'guide': None,
         'a': ('button', 1), 'b': ('button', 0), 'x': ('button', 4), 'y': ('button', 3),
         'leftshoulder': ('button', 6), 'leftstick': None, 'rightshoulder': ('button', 7),
         'rightstick': None, 'back': ('button', 10), 'start': ('button', 11), 'dpup': None,
         'dpdown': None, 'dpleft': None, 'dpright': None, 'lefttrigger': None,
         'righttrigger': None, 'leftx': ('axis', 0), 'lefty': ('axis', 1), 'rightx': None,
         'righty': None},
        {'guid': '05000000a00500003232000008010000', 'name': '8Bitdo Zero GamePad', 'guide': None,
         'a': ('button', 0), 'b': ('button', 1), 'x': ('button', 3), 'y': ('button', 4),
         'leftshoulder': ('button', 6), 'leftstick': None, 'rightshoulder': ('button', 7),
         'rightstick': None, 'back': ('button', 10), 'start': ('button', 11), 'dpup': None,
         'dpdown': None, 'dpleft': None, 'dpright': None, 'lefttrigger': None,
         'righttrigger': None, 'leftx': None, 'lefty': None, 'rightx': None, 'righty': None},
        {'guid': '03000000100000008200000011010000', 'name': 'Akishop Customs PS360+ v1.66',
         'guide': ('button', 8), 'a': ('button', 1), 'b': ('button', 2), 'x': ('button', 0),
         'y': ('button', 3), 'leftshoulder': ('button', 4), 'leftstick': None,
         'rightshoulder': ('button', 5), 'rightstick': None, 'back': ('button', 12),
         'start': ('button', 9), 'dpup': ('hat0', 1), 'dpdown': ('hat0', 4), 'dpleft': ('hat0', 8),
         'dpright': ('hat0', 2), 'lefttrigger': ('button', 6), 'righttrigger': ('button', 7),
         'leftx': None, 'lefty': None, 'rightx': None, 'righty': None},
        {'guid': '03000000e82000006058000001010000', 'name': 'Cideko AK08b', 'guide': None,
         'a': ('button', 2), 'b': ('button', 1), 'x': ('button', 3), 'y': ('button', 0),
         'leftshoulder': ('button', 4), 'leftstick': ('button', 10),
         'rightshoulder': ('button', 5), 'rightstick': ('button', 11), 'back': ('button', 8),
         'start': ('button', 9), 'dpup': ('hat0', 1), 'dpdown': ('hat0', 4), 'dpleft': ('hat0', 8),
         'dpright': ('hat0', 2), 'lefttrigger': ('button', 6), 'righttrigger': ('button', 7),
         'leftx': ('axis', 0), 'lefty': ('axis', 1), 'rightx': ('axis', 2), 'righty': ('axis', 3)},
        {'guid': '03000000260900008888000000010000', 'name': 'Cyber Gadget GameCube Controller',
         'guide': None, 'a': ('button', 0), 'b': ('button', 1), 'x': ('button', 2),
         'y': ('button', 3), 'leftshoulder': None, 'leftstick': None,
         'rightshoulder': ('button', 6), 'rightstick': None, 'back': None, 'start': ('button', 7),
         'dpup': ('hat0', 1), 'dpdown': ('hat0', 4), 'dpleft': ('hat0', 8), 'dpright': ('hat0', 2),
         'lefttrigger': ('axis', 4), 'righttrigger': ('axis', 5), 'leftx': ('axis', 0),
         'lefty': ('axis', 1), 'rightx': ('axis', 2), 'righty': ('axis', 3)},
        {'guid': '03000000790000000600000010010000',
         'name': 'DragonRise Inc. Generic USB Joystick', 'guide': None, 'a': ('button', 2),
         'b': ('button', 1), 'x': ('button', 3), 'y': ('button', 0), 'leftshoulder': ('button', 4),
         'leftstick': ('button', 10), 'rightshoulder': ('button', 5), 'rightstick': ('button', 11),
         'back': ('button', 8), 'start': ('button', 9), 'dpup': ('hat0', 1), 'dpdown': ('hat0', 4),
         'dpleft': ('hat0', 8), 'dpright': ('hat0', 2), 'lefttrigger': ('button', 6),
         'righttrigger': ('button', 7), 'leftx': ('axis', 0), 'lefty': ('axis', 1),
         'rightx': ('axis', 3), 'righty': ('axis', 4)},
        {'guid': '030000006f0e00000104000000010000', 'name': 'Gamestop Logic3 Controller',
         'guide': ('button', 8), 'a': ('button', 0), 'b': ('button', 1), 'x': ('button', 2),
         'y': ('button', 3), 'leftshoulder': ('button', 4), 'leftstick': ('button', 9),
         'rightshoulder': ('button', 5), 'rightstick': ('button', 10), 'back': ('button', 6),
         'start': ('button', 7), 'dpup': ('hat0', 1), 'dpdown': ('hat0', 4), 'dpleft': ('hat0', 8),
         'dpright': ('hat0', 2), 'lefttrigger': ('axis', 2), 'righttrigger': ('axis', 5),
         'leftx': ('axis', 0), 'lefty': ('axis', 1), 'rightx': ('axis', 3), 'righty': ('axis', 4)},
        {'guid': '030000000d0f00005f00000011010000', 'name': 'Hori Fighting Commander 4 (PS3)',
         'guide': ('button', 12), 'a': ('button', 1), 'b': ('button', 2), 'x': ('button', 0),
         'y': ('button', 3), 'leftshoulder': ('button', 4), 'leftstick': None,
         'rightshoulder': ('button', 5), 'rightstick': None, 'back': ('button', 8),
         'start': ('button', 9), 'dpup': ('hat0', 1), 'dpdown': ('hat0', 4), 'dpleft': ('hat0', 8),
         'dpright': ('hat0', 2), 'lefttrigger': ('button', 6), 'righttrigger': ('button', 7),
         'leftx': ('axis', 0), 'lefty': ('axis', 1), 'rightx': ('axis', 2), 'righty': ('axis', 3)},
        {'guid': '030000000d0f00005e00000011010000', 'name': 'Hori Fighting Commander 4 (PS4)',
         'guide': ('button', 12), 'a': ('button', 1), 'b': ('button', 2), 'x': ('button', 0),
         'y': ('button', 3), 'leftshoulder': ('button', 4), 'leftstick': None,
         'rightshoulder': ('button', 5), 'rightstick': None, 'back': ('button', 8),
         'start': ('button', 9), 'dpup': ('hat0', 1), 'dpdown': ('hat0', 4), 'dpleft': ('hat0', 8),
         'dpright': ('hat0', 2), 'lefttrigger': ('axis', 3), 'righttrigger': ('axis', 4),
         'leftx': ('axis', 0), 'lefty': ('axis', 1), 'rightx': ('axis', 2), 'righty': ('axis', 5)},
        {'guid': '030000008f0e00001330000010010000', 'name': 'HuiJia SNES Controller',
         'guide': None, 'a': ('button', 2), 'b': ('button', 1), 'x': ('button', 3),
         'y': ('button', 0), 'leftshoulder': ('button', 6), 'leftstick': None,
         'rightshoulder': ('button', 7), 'rightstick': None, 'back': ('button', 8),
         'start': ('button', 9), 'dpup': None, 'dpdown': None, 'dpleft': None, 'dpright': None,
         'lefttrigger': None, 'righttrigger': None, 'leftx': None, 'lefty': None, 'rightx': None,
         'righty': None},
        {'guid': '030000006d04000016c2000011010000', 'name': 'Logitech Dual Action', 'guide': None,
         'a': ('button', 1), 'b': ('button', 2), 'x': ('button', 0), 'y': ('button', 3),
         'leftshoulder': ('button', 4), 'leftstick': ('button', 10),
         'rightshoulder': ('button', 5), 'rightstick': ('button', 11), 'back': ('button', 8),
         'start': ('button', 9), 'dpup': ('hat0', 1), 'dpdown': ('hat0', 4), 'dpleft': ('hat0', 8),
         'dpright': ('hat0', 2), 'lefttrigger': ('button', 6), 'righttrigger': ('button', 7),
         'leftx': ('axis', 0), 'lefty': ('axis', 1), 'rightx': ('axis', 2), 'righty': ('axis', 3)},
        {'guid': '030000006d04000016c2000010010000', 'name': 'Logitech Dual Action', 'guide': None,
         'a': ('button', 1), 'b': ('button', 2), 'x': ('button', 0), 'y': ('button', 3),
         'leftshoulder': ('button', 4), 'leftstick': ('button', 10),
         'rightshoulder': ('button', 5), 'rightstick': ('button', 11), 'back': ('button', 8),
         'start': ('button', 9), 'dpup': ('hat0', 1), 'dpdown': ('hat0', 4), 'dpleft': ('hat0', 8),
         'dpright': ('hat0', 2), 'lefttrigger': ('button', 6), 'righttrigger': ('button', 7),
         'leftx': ('axis', 0), 'lefty': ('axis', 1), 'rightx': ('axis', 2), 'righty': ('axis', 3)},
        {'guid': '030000006d04000018c2000010010000', 'name': 'Logitech RumblePad 2', 'guide': None,
         'a': ('button', 1), 'b': ('button', 2), 'x': ('button', 0), 'y': ('button', 3),
         'leftshoulder': ('button', 4), 'leftstick': ('button', 10),
         'rightshoulder': ('button', 5), 'rightstick': ('button', 11), 'back': ('button', 8),
         'start': ('button', 9), 'dpup': ('hat0', 1), 'dpdown': ('hat0', 4), 'dpleft': ('hat0', 8),
         'dpright': ('hat0', 2), 'lefttrigger': ('button', 6), 'righttrigger': ('button', 7),
         'leftx': ('axis', 0), 'lefty': ('axis', 1), 'rightx': ('axis', 2), 'righty': ('axis', 3)},
        {'guid': '03000000380700008433000011010000', 'name': 'Mad Catz FightStick TE S+ PS3',
         'guide': ('button', 12), 'a': ('button', 1), 'b': ('button', 2), 'x': ('button', 0),
         'y': ('button', 3), 'leftshoulder': ('button', 4), 'leftstick': None,
         'rightshoulder': ('button', 5), 'rightstick': None, 'back': ('button', 8),
         'start': ('button', 9), 'dpup': ('hat0', 1), 'dpdown': ('hat0', 4), 'dpleft': ('hat0', 8),
         'dpright': ('hat0', 2), 'lefttrigger': ('button', 6), 'righttrigger': ('button', 7),
         'leftx': ('axis', 0), 'lefty': ('axis', 1), 'rightx': ('axis', 2), 'righty': ('axis', 3)},
        {'guid': '03000000380700008483000011010000', 'name': 'Mad Catz FightStick TE S+ PS4',
         'guide': ('button', 12), 'a': ('button', 1), 'b': ('button', 2), 'x': ('button', 0),
         'y': ('button', 3), 'leftshoulder': ('button', 4), 'leftstick': None,
         'rightshoulder': ('button', 5), 'rightstick': None, 'back': ('button', 8),
         'start': ('button', 9), 'dpup': ('hat0', 1), 'dpdown': ('hat0', 4), 'dpleft': ('hat0', 8),
         'dpright': ('hat0', 2), 'lefttrigger': ('axis', 3), 'righttrigger': ('axis', 4),
         'leftx': ('axis', 0), 'lefty': ('axis', 1), 'rightx': ('axis', 2), 'righty': ('axis', 5)},
        {'guid': '03000000380700003847000090040000',
         'name': 'Mad Catz Wired Xbox 360 Controller (SFIV)', 'guide': ('button', 10),
         'a': ('button', 0), 'b': ('button', 1), 'x': ('button', 2), 'y': ('button', 3),
         'leftshoulder': ('button', 4), 'leftstick': None, 'rightshoulder': ('button', 5),
         'rightstick': None, 'back': ('button', 8), 'start': ('button', 9), 'dpup': ('hat0', 1),
         'dpdown': ('hat0', 4), 'dpleft': ('hat0', 8), 'dpright': ('hat0', 2),
         'lefttrigger': ('button', 6), 'righttrigger': ('button', 7), 'leftx': ('axis', 0),
         'lefty': ('axis', 1), 'rightx': ('axis', 2), 'righty': ('axis', 3)},
        {'guid': '03000000380700008034000011010000', 'name': 'Mad Catz fightstick (PS3)',
         'guide': ('button', 12), 'a': ('button', 1), 'b': ('button', 2), 'x': ('button', 0),
         'y': ('button', 3), 'leftshoulder': ('button', 4), 'leftstick': None,
         'rightshoulder': ('button', 5), 'rightstick': None, 'back': ('button', 8),
         'start': ('button', 9), 'dpup': ('hat0', 1), 'dpdown': ('hat0', 4), 'dpleft': ('hat0', 8),
         'dpright': ('hat0', 2), 'lefttrigger': ('button', 6), 'righttrigger': ('button', 7),
         'leftx': ('axis', 0), 'lefty': ('axis', 1), 'rightx': ('axis', 2), 'righty': ('axis', 3)},
        {'guid': '03000000380700008084000011010000', 'name': 'Mad Catz fightstick (PS4)',
         'guide': ('button', 12), 'a': ('button', 1), 'b': ('button', 2), 'x': ('button', 0),
         'y': ('button', 3), 'leftshoulder': ('button', 4), 'leftstick': None,
         'rightshoulder': ('button', 5), 'rightstick': None, 'back': ('button', 8),
         'start': ('button', 9), 'dpup': ('hat0', 1), 'dpdown': ('hat0', 4), 'dpleft': ('hat0', 8),
         'dpright': ('hat0', 2), 'lefttrigger': ('axis', 3), 'righttrigger': ('axis', 4),
         'leftx': ('axis', 0), 'lefty': ('axis', 1), 'rightx': ('axis', 2), 'righty': ('axis', 5)},
        {'guid': '03000000380700001888000010010000', 'name': 'MadCatz PC USB Wired Stick 8818',
         'guide': ('button', 12), 'a': ('button', 1), 'b': ('button', 2), 'x': ('button', 0),
         'y': ('button', 3), 'leftshoulder': ('button', 4), 'leftstick': None,
         'rightshoulder': ('button', 5), 'rightstick': None, 'back': ('button', 8),
         'start': ('button', 9), 'dpup': ('hat0', 1), 'dpdown': ('hat0', 4), 'dpleft': ('hat0', 8),
         'dpright': ('hat0', 2), 'lefttrigger': ('button', 6), 'righttrigger': ('button', 7),
         'leftx': ('axis', 0), 'lefty': ('axis', 1), 'rightx': ('axis', 2), 'righty': ('axis', 3)},
        {'guid': '03000000790000004418000010010000', 'name': 'Mayflash GameCube Controller',
         'guide': None, 'a': ('button', 1), 'b': ('button', 2), 'x': ('button', 0),
         'y': ('button', 3), 'leftshoulder': None, 'leftstick': None,
         'rightshoulder': ('button', 7), 'rightstick': None, 'back': None, 'start': ('button', 9),
         'dpup': ('button', 12), 'dpdown': ('button', 14), 'dpleft': ('button', 15),
         'dpright': ('button', 13), 'lefttrigger': ('axis', 3), 'righttrigger': ('axis', 4),
         'leftx': ('axis', 0), 'lefty': ('axis', 1), 'rightx': ('axis', 5), 'righty': ('axis', 2)},
        {'guid': '030000001008000001e5000010010000', 'name': 'NEXT SNES Controller', 'guide': None,
         'a': ('button', 2), 'b': ('button', 1), 'x': ('button', 3), 'y': ('button', 0),
         'leftshoulder': ('button', 4), 'leftstick': None, 'rightshoulder': ('button', 6),
         'rightstick': None, 'back': ('button', 8), 'start': ('button', 9), 'dpup': None,
         'dpdown': None, 'dpleft': None, 'dpright': None, 'lefttrigger': None,
         'righttrigger': None, 'leftx': None, 'lefty': None, 'rightx': None, 'righty': None},
        {'guid': '03000000550900001072000011010000', 'name': 'NVIDIA Controller',
         'guide': ('button', 13), 'a': ('button', 0), 'b': ('button', 1), 'x': ('button', 2),
         'y': ('button', 3), 'leftshoulder': ('button', 4), 'leftstick': ('button', 8),
         'rightshoulder': ('button', 5), 'rightstick': ('button', 9), 'back': None,
         'start': ('button', 7), 'dpup': ('hat0', 1), 'dpdown': ('hat0', 4), 'dpleft': ('hat0', 8),
         'dpright': ('hat0', 2), 'lefttrigger': ('axis', 5), 'righttrigger': ('axis', 4),
         'leftx': ('axis', 0), 'lefty': ('axis', 1), 'rightx': ('axis', 2), 'righty': ('axis', 3)},
        {'guid': '050000007e0500003003000001000000', 'name': 'Nintendo Wii Remote Pro Controller',
         'guide': ('button', 10), 'a': ('button', 0), 'b': ('button', 1), 'x': ('button', 3),
         'y': ('button', 2), 'leftshoulder': ('button', 4), 'leftstick': ('button', 11),
         'rightshoulder': ('button', 5), 'rightstick': ('button', 12), 'back': ('button', 8),
         'start': ('button', 9), 'dpup': ('button', 13), 'dpdown': ('button', 14),
         'dpleft': ('button', 15), 'dpright': ('button', 16), 'lefttrigger': ('button', 6),
         'righttrigger': ('button', 7), 'leftx': ('axis', 0), 'lefty': ('axis', 1),
         'rightx': ('axis', 2), 'righty': ('axis', 3)},
        {'guid': '030000000d0500000308000010010000', 'name': 'Nostromo n45 Dual Analog Gamepad',
         'guide': ('button', 9), 'a': ('button', 0), 'b': ('button', 1), 'x': ('button', 2),
         'y': ('button', 3), 'leftshoulder': ('button', 4), 'leftstick': ('button', 12),
         'rightshoulder': ('button', 6), 'rightstick': ('button', 11), 'back': ('button', 8),
         'start': ('button', 10), 'dpup': ('hat0', 1), 'dpdown': ('hat0', 4),
         'dpleft': ('hat0', 8), 'dpright': ('hat0', 2), 'lefttrigger': ('button', 5),
         'righttrigger': ('button', 7), 'leftx': ('axis', 0), 'lefty': ('axis', 1),
         'rightx': ('axis', 3), 'righty': ('axis', 2)},
        {'guid': '05000000362800000100000002010000', 'name': 'OUYA Game Controller',
         'guide': ('button', 14), 'a': ('button', 0), 'b': ('button', 3), 'x': ('button', 1),
         'y': ('button', 2), 'leftshoulder': ('button', 4), 'leftstick': ('button', 6),
         'rightshoulder': ('button', 5), 'rightstick': ('button', 7), 'back': None, 'start': None,
         'dpup': ('button', 8), 'dpdown': ('button', 9), 'dpleft': ('button', 10),
         'dpright': ('button', 11), 'lefttrigger': ('axis', 2), 'righttrigger': ('axis', 5),
         'leftx': ('axis', 0), 'lefty': ('axis', 1), 'rightx': ('axis', 3), 'righty': ('axis', 4)},
        {'guid': '030000004c0500006802000010010000', 'name': 'PS3 Controller',
         'guide': ('button', 16), 'a': ('button', 14), 'b': ('button', 13), 'x': ('button', 15),
         'y': ('button', 12), 'leftshoulder': ('button', 10), 'leftstick': ('button', 1),
         'rightshoulder': ('button', 11), 'rightstick': ('button', 2), 'back': ('button', 0),
         'start': ('button', 3), 'dpup': ('button', 4), 'dpdown': ('button', 6),
         'dpleft': ('button', 7), 'dpright': ('button', 5), 'lefttrigger': ('button', 8),
         'righttrigger': ('button', 9), 'leftx': ('axis', 0), 'lefty': ('axis', 1),
         'rightx': ('axis', 2), 'righty': ('axis', 3)},
        {'guid': '050000004c0500006802000000010000', 'name': 'PS3 Controller',
         'guide': ('button', 16), 'a': ('button', 14), 'b': ('button', 13), 'x': ('button', 15),
         'y': ('button', 12), 'leftshoulder': ('button', 10), 'leftstick': ('button', 1),
         'rightshoulder': ('button', 11), 'rightstick': ('button', 2), 'back': ('button', 0),
         'start': ('button', 3), 'dpup': ('button', 4), 'dpdown': ('button', 6),
         'dpleft': ('button', 7), 'dpright': ('button', 5), 'lefttrigger': ('axis', 12),
         'righttrigger': ('axis', 13), 'leftx': ('axis', 0), 'lefty': ('axis', 1),
         'rightx': ('axis', 2), 'righty': ('axis', 3)},
        {'guid': '03000000341a00003608000011010000', 'name': 'PS3 Controller',
         'guide': ('button', 12), 'a': ('button', 1), 'b': ('button', 2), 'x': ('button', 0),
         'y': ('button', 3), 'leftshoulder': ('button', 4), 'leftstick': ('button', 10),
         'rightshoulder': ('button', 5), 'rightstick': ('button', 11), 'back': ('button', 8),
         'start': ('button', 9), 'dpup': ('hat0', 1), 'dpdown': ('hat0', 4), 'dpleft': ('hat0', 8),
         'dpright': ('hat0', 2), 'lefttrigger': ('button', 6), 'righttrigger': ('button', 7),
         'leftx': ('axis', 0), 'lefty': ('axis', 1), 'rightx': ('axis', 2), 'righty': ('axis', 3)},
        {'guid': '050000004c050000c405000000010000', 'name': 'PS4 Controller',
         'guide': ('button', 12), 'a': ('button', 1), 'b': ('button', 2), 'x': ('button', 0),
         'y': ('button', 3), 'leftshoulder': ('button', 4), 'leftstick': ('button', 10),
         'rightshoulder': ('button', 5), 'rightstick': ('button', 11), 'back': ('button', 8),
         'start': ('button', 9), 'dpup': ('hat0', 1), 'dpdown': ('hat0', 4), 'dpleft': ('hat0', 8),
         'dpright': ('hat0', 2), 'lefttrigger': ('axis', 3), 'righttrigger': ('axis', 4),
         'leftx': ('axis', 0), 'lefty': ('axis', 1), 'rightx': ('axis', 2), 'righty': ('axis', 5)},
        {'guid': '030000004c050000cc09000011010000', 'name': 'PS4 Controller',
         'guide': ('button', 12), 'a': ('button', 1), 'b': ('button', 2), 'x': ('button', 0),
         'y': ('button', 3), 'leftshoulder': ('button', 4), 'leftstick': ('button', 10),
         'rightshoulder': ('button', 5), 'rightstick': ('button', 11), 'back': ('button', 8),
         'start': ('button', 9), 'dpup': ('hat0', 1), 'dpdown': ('hat0', 4), 'dpleft': ('hat0', 8),
         'dpright': ('hat0', 2), 'lefttrigger': ('axis', 3), 'righttrigger': ('axis', 4),
         'leftx': ('axis', 0), 'lefty': ('axis', 1), 'rightx': ('axis', 2), 'righty': ('axis', 5)},
        {'guid': '050000004c050000cc09000000010000', 'name': 'PS4 Controller',
         'guide': ('button', 12), 'a': ('button', 1), 'b': ('button', 2), 'x': ('button', 0),
         'y': ('button', 3), 'leftshoulder': ('button', 4), 'leftstick': ('button', 10),
         'rightshoulder': ('button', 5), 'rightstick': ('button', 11), 'back': ('button', 8),
         'start': ('button', 9), 'dpup': ('hat0', 1), 'dpdown': ('hat0', 4), 'dpleft': ('hat0', 8),
         'dpright': ('hat0', 2), 'lefttrigger': ('axis', 3), 'righttrigger': ('axis', 4),
         'leftx': ('axis', 0), 'lefty': ('axis', 1), 'rightx': ('axis', 2), 'righty': ('axis', 5)},
        {'guid': '030000004c050000a00b000011010000', 'name': 'PS4 Controller',
         'guide': ('button', 12), 'a': ('button', 1), 'b': ('button', 2), 'x': ('button', 0),
         'y': ('button', 3), 'leftshoulder': ('button', 4), 'leftstick': ('button', 10),
         'rightshoulder': ('button', 5), 'rightstick': ('button', 11), 'back': ('button', 8),
         'start': ('button', 9), 'dpup': ('hat0', 1), 'dpdown': ('hat0', 4), 'dpleft': ('hat0', 8),
         'dpright': ('hat0', 2), 'lefttrigger': ('axis', 3), 'righttrigger': ('axis', 4),
         'leftx': ('axis', 0), 'lefty': ('axis', 1), 'rightx': ('axis', 2), 'righty': ('axis', 5)},
        {'guid': '030000004c050000c405000011810000', 'name': 'PS4 Controller',
         'guide': ('button', 10), 'a': ('button', 0), 'b': ('button', 1), 'x': ('button', 3),
         'y': ('button', 2), 'leftshoulder': ('button', 4), 'leftstick': ('button', 11),
         'rightshoulder': ('button', 5), 'rightstick': ('button', 12), 'back': ('button', 8),
         'start': ('button', 9), 'dpup': ('hat0', 1), 'dpdown': ('hat0', 4), 'dpleft': ('hat0', 8),
         'dpright': ('hat0', 2), 'lefttrigger': ('axis', 2), 'righttrigger': ('axis', 5),
         'leftx': ('axis', 0), 'lefty': ('axis', 1), 'rightx': ('axis', 3), 'righty': ('axis', 4)},
        {'guid': '050000004c050000c405000000810000', 'name': 'PS4 Controller',
         'guide': ('button', 10), 'a': ('button', 0), 'b': ('button', 1), 'x': ('button', 3),
         'y': ('button', 2), 'leftshoulder': ('button', 4), 'leftstick': ('button', 11),
         'rightshoulder': ('button', 5), 'rightstick': ('button', 12), 'back': ('button', 8),
         'start': ('button', 9), 'dpup': ('hat0', 1), 'dpdown': ('hat0', 4), 'dpleft': ('hat0', 8),
         'dpright': ('hat0', 2), 'lefttrigger': ('axis', 2), 'righttrigger': ('axis', 5),
         'leftx': ('axis', 0), 'lefty': ('axis', 1), 'rightx': ('axis', 3), 'righty': ('axis', 4)},
        {'guid': '030000004c050000cc09000011810000', 'name': 'PS4 Controller',
         'guide': ('button', 10), 'a': ('button', 0), 'b': ('button', 1), 'x': ('button', 3),
         'y': ('button', 2), 'leftshoulder': ('button', 4), 'leftstick': ('button', 11),
         'rightshoulder': ('button', 5), 'rightstick': ('button', 12), 'back': ('button', 8),
         'start': ('button', 9), 'dpup': ('hat0', 1), 'dpdown': ('hat0', 4), 'dpleft': ('hat0', 8),
         'dpright': ('hat0', 2), 'lefttrigger': ('axis', 2), 'righttrigger': ('axis', 5),
         'leftx': ('axis', 0), 'lefty': ('axis', 1), 'rightx': ('axis', 3), 'righty': ('axis', 4)},
        {'guid': '050000004c050000cc09000000810000', 'name': 'PS4 Controller',
         'guide': ('button', 10), 'a': ('button', 0), 'b': ('button', 1), 'x': ('button', 3),
         'y': ('button', 2), 'leftshoulder': ('button', 4), 'leftstick': ('button', 11),
         'rightshoulder': ('button', 5), 'rightstick': ('button', 12), 'back': ('button', 8),
         'start': ('button', 9), 'dpup': ('hat0', 1), 'dpdown': ('hat0', 4), 'dpleft': ('hat0', 8),
         'dpright': ('hat0', 2), 'lefttrigger': ('axis', 2), 'righttrigger': ('axis', 5),
         'leftx': ('axis', 0), 'lefty': ('axis', 1), 'rightx': ('axis', 3), 'righty': ('axis', 4)},
        {'guid': '030000004c050000a00b000011810000', 'name': 'PS4 Controller',
         'guide': ('button', 10), 'a': ('button', 0), 'b': ('button', 1), 'x': ('button', 3),
         'y': ('button', 2), 'leftshoulder': ('button', 4), 'leftstick': ('button', 11),
         'rightshoulder': ('button', 5), 'rightstick': ('button', 12), 'back': ('button', 8),
         'start': ('button', 9), 'dpup': ('hat0', 1), 'dpdown': ('hat0', 4), 'dpleft': ('hat0', 8),
         'dpright': ('hat0', 2), 'lefttrigger': ('axis', 2), 'righttrigger': ('axis', 5),
         'leftx': ('axis', 0), 'lefty': ('axis', 1), 'rightx': ('axis', 3), 'righty': ('axis', 4)},
        {'guid': '03000000c6240000045d000025010000', 'name': 'Razer Sabertooth',
         'guide': ('button', 8), 'a': ('button', 0), 'b': ('button', 1), 'x': ('button', 2),
         'y': ('button', 3), 'leftshoulder': ('button', 4), 'leftstick': ('button', 9),
         'rightshoulder': ('button', 5), 'rightstick': ('button', 10), 'back': ('button', 6),
         'start': ('button', 7), 'dpup': ('hat0', 1), 'dpdown': ('hat0', 4), 'dpleft': ('hat0', 8),
         'dpright': ('hat0', 2), 'lefttrigger': ('axis', 2), 'righttrigger': ('axis', 5),
         'leftx': ('axis', 0), 'lefty': ('axis', 1), 'rightx': ('axis', 3), 'righty': ('axis', 4)},
        {'guid': '03000000321500000009000011010000', 'name': 'Razer Serval',
         'guide': ('button', 8), 'a': ('button', 0), 'b': ('button', 1), 'x': ('button', 2),
         'y': ('button', 3), 'leftshoulder': ('button', 4), 'leftstick': ('button', 9),
         'rightshoulder': ('button', 5), 'rightstick': ('button', 10), 'back': ('button', 6),
         'start': ('button', 7), 'dpup': ('hat0', 1), 'dpdown': ('hat0', 4), 'dpleft': ('hat0', 8),
         'dpright': ('hat0', 2), 'lefttrigger': ('axis', 5), 'righttrigger': ('axis', 4),
         'leftx': ('axis', 0), 'lefty': ('axis', 1), 'rightx': ('axis', 2), 'righty': ('axis', 3)},
        {'guid': '050000003215000000090000163a0000', 'name': 'Razer Serval',
         'guide': ('button', 8), 'a': ('button', 0), 'b': ('button', 1), 'x': ('button', 2),
         'y': ('button', 3), 'leftshoulder': ('button', 4), 'leftstick': ('button', 9),
         'rightshoulder': ('button', 5), 'rightstick': ('button', 10), 'back': ('button', 6),
         'start': ('button', 7), 'dpup': ('hat0', 1), 'dpdown': ('hat0', 4), 'dpleft': ('hat0', 8),
         'dpright': ('hat0', 2), 'lefttrigger': ('axis', 5), 'righttrigger': ('axis', 4),
         'leftx': ('axis', 0), 'lefty': ('axis', 1), 'rightx': ('axis', 2), 'righty': ('axis', 3)},
        {'guid': '0300000032150000030a000001010000', 'name': 'Razer Wildcat',
         'guide': ('button', 8), 'a': ('button', 0), 'b': ('button', 1), 'x': ('button', 2),
         'y': ('button', 3), 'leftshoulder': ('button', 4), 'leftstick': ('button', 9),
         'rightshoulder': ('button', 5), 'rightstick': ('button', 10), 'back': ('button', 6),
         'start': ('button', 7), 'dpup': ('hat0', 1), 'dpdown': ('hat0', 4), 'dpleft': ('hat0', 8),
         'dpright': ('hat0', 2), 'lefttrigger': ('axis', 2), 'righttrigger': ('axis', 5),
         'leftx': ('axis', 0), 'lefty': ('axis', 1), 'rightx': ('axis', 3), 'righty': ('axis', 4)},
        {'guid': '03000000790000001100000010010000', 'name': 'Retrolink SNES Controller',
         'guide': None, 'a': ('button', 2), 'b': ('button', 1), 'x': ('button', 3),
         'y': ('button', 0), 'leftshoulder': ('button', 4), 'leftstick': None,
         'rightshoulder': ('button', 5), 'rightstick': None, 'back': ('button', 8),
         'start': ('button', 9), 'dpup': None, 'dpdown': None, 'dpleft': None, 'dpright': None,
         'lefttrigger': None, 'righttrigger': None, 'leftx': None, 'lefty': None, 'rightx': None,
         'righty': None},
        {'guid': '03000000de280000fc11000001000000', 'name': 'Steam Controller',
         'guide': ('button', 8), 'a': ('button', 0), 'b': ('button', 1),
         'x': ('button', 2), 'y': ('button', 3), 'leftshoulder': ('button', 4),
         'leftstick': ('button', 9), 'rightshoulder': ('button', 5),
         'rightstick': ('button', 10), 'back': ('button', 6),
         'start': ('button', 7), 'dpup': ('hat0', 1), 'dpdown': ('hat0', 4),
         'dpleft': ('hat0', 8), 'dpright': ('hat0', 2),
         'lefttrigger': ('axis', 2), 'righttrigger': ('axis', 5),
         'leftx': ('axis', 0), 'lefty': ('axis', 1), 'rightx': ('axis', 3),
         'righty': ('axis', 4)},
        {'guid': 'xinput', 'name': 'XInput Controller', 'guide': ('button', 8), 'a': ('button', 0),
         'b': ('button', 1), 'x': ('button', 2), 'y': ('button', 3), 'leftshoulder': ('button', 4),
         'leftstick': ('button', 9), 'rightshoulder': ('button', 5), 'rightstick': ('button', 10),
         'back': ('button', 6), 'start': ('button', 7), 'dpup': ('hat0', 1), 'dpdown': ('hat0', 4),
         'dpleft': ('hat0', 8), 'dpright': ('hat0', 2), 'lefttrigger': ('axis', 2),
         'righttrigger': ('axis', 5), 'leftx': ('axis', 0), 'lefty': ('axis', 1),
         'rightx': ('axis', 3), 'righty': ('axis', 4)},
        {'guid': '050000005e040000e002000003090000', 'name': 'Xbox One Wireless Controller',
         'guide': ('button', 10), 'a': ('button', 0), 'b': ('button', 1), 'x': ('button', 2),
         'y': ('button', 3), 'leftshoulder': ('button', 4), 'leftstick': ('button', 8),
         'rightshoulder': ('button', 5), 'rightstick': ('button', 9), 'back': ('button', 6),
         'start': ('button', 7), 'dpup': ('hat0', 1), 'dpdown': ('hat0', 4), 'dpleft': ('hat0', 8),
         'dpright': ('hat0', 2), 'lefttrigger': ('axis', 2), 'righttrigger': ('axis', 5),
         'leftx': ('axis', 0), 'lefty': ('axis', 1), 'rightx': ('axis', 3), 'righty': ('axis', 4)},
        {'guid': '050000005e040000fd02000003090000', 'name': 'Xbox One Wireless Controller',
         'guide': ('button', 16), 'a': ('button', 0), 'b': ('button', 1), 'x': ('button', 3),
         'y': ('button', 4), 'leftshoulder': ('button', 6), 'leftstick': ('button', 13),
         'rightshoulder': ('button', 7), 'rightstick': ('button', 14), 'back': ('button', 15),
         'start': ('button', 11), 'dpup': ('hat0', 1), 'dpdown': ('hat0', 4),
         'dpleft': ('hat0', 8), 'dpright': ('hat0', 2), 'lefttrigger': ('axis', 5),
         'righttrigger': ('axis', 4), 'leftx': ('axis', 0), 'lefty': ('axis', 1),
         'rightx': ('axis', 2), 'righty': ('axis', 3)},
        {'guid': '05000000172700004431000029010000', 'name': 'XiaoMi Game Controller',
         'guide': ('button', 20), 'a': ('button', 0), 'b': ('button', 1), 'x': ('button', 3),
         'y': ('button', 4), 'leftshoulder': ('button', 6), 'leftstick': ('button', 13),
         'rightshoulder': ('button', 7), 'rightstick': ('button', 14), 'back': ('button', 10),
         'start': ('button', 11), 'dpup': ('hat0', 1), 'dpdown': ('hat0', 4),
         'dpleft': ('hat0', 8), 'dpright': ('hat0', 2), 'lefttrigger': ('axis', 7),
         'righttrigger': ('axis', 6), 'leftx': ('axis', 0), 'lefty': ('axis', 1),
         'rightx': ('axis', 2), 'righty': ('axis', 5)},
        {'guid': '03000000830500006020000010010000', 'name': 'iBuffalo SNES Controller',
         'guide': None, 'a': ('button', 1), 'b': ('button', 0), 'x': ('button', 3),
         'y': ('button', 2), 'leftshoulder': ('button', 4), 'leftstick': None,
         'rightshoulder': ('button', 5), 'rightstick': None, 'back': ('button', 6),
         'start': ('button', 7), 'dpup': None, 'dpdown': None, 'dpleft': None, 'dpright': None,
         'lefttrigger': None, 'righttrigger': None, 'leftx': None, 'lefty': None, 'rightx': None,
         'righty': None}]
elif compat_platform.startswith("win"):
    mapping_list = [
        {'lefttrigger': ('button', 5), 'leftshoulder': ('button', 4),
         'dpright': ('hat0', 2), 'platform': 'Windows', 'y': ('button', 3),
         'guide': None,
         'name': 'Acme', 'lefty': ('axis', 1), 'start': ('button', 9),
         'righttrigger': ('button', 7), 'rightx': ('axis', 3), 'x': ('button', 2),
         'dpdown': ('hat0', 4), 'dpleft': ('hat0', 8), 'back': ('button', 8),
         'dpup': ('hat0', 1), 'righty': ('axis', 2), 'a': ('button', 0),
         'b': ('button', 1),
         'leftx': ('axis', 0), 'rightstick': ('button', 11),
         'leftstick': ('button', 10),
         'rightshoulder': ('button', 6), 'guid': '8f0e1200000000000000504944564944'},
        {'lefttrigger': ('button', 6), 'leftshoulder': ('button', 4),
         'dpright': ('hat0', 2), 'platform': 'Windows', 'y': ('button', 3),
         'guide': ('button', 12), 'name': 'Afterglow PS3 Controller',
         'lefty': ('axis', 1),
         'start': ('button', 9), 'righttrigger': ('button', 7), 'rightx': ('axis', 2),
         'x': ('button', 0), 'dpdown': ('hat0', 4), 'dpleft': ('hat0', 8),
         'back': ('button', 8), 'dpup': ('hat0', 1), 'righty': ('axis', 3),
         'a': ('button', 1), 'b': ('button', 2), 'leftx': ('axis', 0),
         'rightstick': ('button', 11), 'leftstick': ('button', 10),
         'rightshoulder': ('button', 5), 'guid': '341a3608000000000000504944564944'},
        {'lefttrigger': ('button', 6), 'leftshoulder': ('button', 4),
         'dpright': ('hat0', 2), 'platform': 'Windows', 'y': ('button', 3),
         'guide': None,
         'name': 'GameStop Gamepad', 'lefty': ('axis', 1), 'start': ('button', 9),
         'righttrigger': ('button', 7), 'rightx': ('axis', 2), 'x': ('button', 2),
         'dpdown': ('hat0', 4), 'dpleft': ('hat0', 8), 'back': ('button', 8),
         'dpup': ('hat0', 1), 'righty': ('axis', 3), 'a': ('button', 0),
         'b': ('button', 1),
         'leftx': ('axis', 0), 'rightstick': ('button', 11),
         'leftstick': ('button', 10),
         'rightshoulder': ('button', 5), 'guid': 'ffff0000000000000000504944564944'},
        {'lefttrigger': ('button', 6), 'leftshoulder': ('button', 4),
         'dpright': ('hat0', 2), 'platform': 'Windows', 'y': ('button', 3),
         'guide': None,
         'name': 'Generic DirectInput Controller', 'lefty': ('axis', 1),
         'start': ('button', 9), 'righttrigger': ('button', 7), 'rightx': ('axis', 2),
         'x': ('button', 0), 'dpdown': ('hat0', 4), 'dpleft': ('hat0', 8),
         'back': ('button', 8), 'dpup': ('hat0', 1), 'righty': ('axis', 3),
         'a': ('button', 1), 'b': ('button', 2), 'leftx': ('axis', 0),
         'rightstick': ('button', 11), 'leftstick': ('button', 10),
         'rightshoulder': ('button', 5), 'guid': '6d0416c2000000000000504944564944'},
        {'lefttrigger': ('button', 6), 'leftshoulder': ('button', 4),
         'dpright': ('hat0', 2), 'platform': 'Windows', 'y': ('button', 3),
         'guide': None,
         'name': 'Logitech F710 Gamepad', 'lefty': ('axis', 1), 'start': ('button', 9),
         'righttrigger': ('button', 7), 'rightx': ('axis', 2), 'x': ('button', 0),
         'dpdown': ('hat0', 4), 'dpleft': ('hat0', 8), 'back': ('button', 8),
         'dpup': ('hat0', 1), 'righty': ('axis', 3), 'a': ('button', 1),
         'b': ('button', 2),
         'leftx': ('axis', 0), 'rightstick': ('button', 11),
         'leftstick': ('button', 10),
         'rightshoulder': ('button', 5), 'guid': '6d0419c2000000000000504944564944'},
        {'lefttrigger': ('button', 6), 'leftshoulder': ('button', 4),
         'dpright': ('hat0', 2), 'platform': 'Windows', 'y': ('button', 3),
         'guide': ('button', 12), 'name': 'PS3 Controller', 'lefty': ('axis', 1),
         'start': ('button', 11), 'righttrigger': ('button', 7), 'rightx': ('axis', 3),
         'x': ('button', 0), 'dpdown': ('hat0', 8), 'dpleft': ('hat0', 4),
         'back': ('button', 8), 'dpup': ('hat0', 1), 'righty': ('axis', 4),
         'a': ('button', 2), 'b': ('button', 1), 'leftx': ('axis', 0),
         'rightstick': ('button', 10), 'leftstick': ('button', 9),
         'rightshoulder': ('button', 5), 'guid': '88880803000000000000504944564944'},
        {'lefttrigger': ('button', 8), 'leftshoulder': ('button', 10),
         'dpright': ('button', 5), 'platform': 'Windows', 'y': ('button', 12),
         'guide': ('button', 16), 'name': 'PS3 Controller', 'lefty': ('axis', 1),
         'start': ('button', 3), 'righttrigger': ('button', 9), 'rightx': ('axis', 2),
         'x': ('button', 15), 'dpdown': ('button', 6), 'dpleft': ('button', 7),
         'back': ('button', 0), 'dpup': ('button', 4), 'righty': ('axis', 3),
         'a': ('button', 14), 'b': ('button', 13), 'leftx': ('axis', 0),
         'rightstick': ('button', 2), 'leftstick': ('button', 1),
         'rightshoulder': ('button', 11), 'guid': '4c056802000000000000504944564944'},
        {'lefttrigger': ('button', 4), 'leftshoulder': ('button', 6),
         'dpright': ('hat0', 2), 'platform': 'Windows', 'y': ('button', 3),
         'guide': None,
         'name': 'PS3 DualShock', 'lefty': ('axis', 1), 'start': ('button', 8),
         'righttrigger': ('button', 5), 'rightx': ('axis', 2), 'x': ('button', 0),
         'dpdown': ('hat0', 8), 'dpleft': ('hat0', 4), 'back': ('button', 9),
         'dpup': ('hat0', 1), 'righty': ('axis', 3), 'a': ('button', 2),
         'b': ('button', 1),
         'leftx': ('axis', 0), 'rightstick': ('button', 11),
         'leftstick': ('button', 10),
         'rightshoulder': ('button', 7), 'guid': '25090500000000000000504944564944'},
        {'lefttrigger': ('axis', 3), 'leftshoulder': ('button', 4),
         'dpright': ('hat0', 2),
         'platform': 'Windows', 'y': ('button', 3), 'guide': ('button', 12),
         'name': 'PS4 Controller', 'lefty': ('axis', 1), 'start': ('button', 9),
         'righttrigger': ('axis', 4), 'rightx': ('axis', 2), 'x': ('button', 0),
         'dpdown': ('hat0', 4), 'dpleft': ('hat0', 8), 'back': ('button', 8),
         'dpup': ('hat0', 1), 'righty': ('axis', 5), 'a': ('button', 1),
         'b': ('button', 2),
         'leftx': ('axis', 0), 'rightstick': ('button', 11),
         'leftstick': ('button', 10),
         'rightshoulder': ('button', 5), 'guid': '4c05c405000000000000504944564944'},
        {'lefttrigger': ('button', 6), 'leftshoulder': ('button', 4),
         'dpright': ('hat0', 2), 'platform': 'Windows', 'y': ('button', 3),
         'guide': None,
         'name': 'Logitech RumblePad 2 USB', 'lefty': ('axis', 1),
         'start': ('button', 9),
         'righttrigger': ('button', 7), 'rightx': ('axis', 2), 'x': ('button', 0),
         'dpdown': ('hat0', 4), 'dpleft': ('hat0', 8), 'back': ('button', 8),
         'dpup': ('hat0', 1), 'righty': ('axis', 3), 'a': ('button', 1),
         'b': ('button', 2),
         'leftx': ('axis', 0), 'rightstick': ('button', 11),
         'leftstick': ('button', 10),
         'rightshoulder': ('button', 5), 'guid': '6d0418c2000000000000504944564944'},
        {'lefttrigger': ('button', 12), 'leftshoulder': ('button', 4),
         'dpright': ('button', 11), 'platform': 'Windows', 'y': ('button', 2),
         'guide': ('button', 15), 'name': 'OUYA Controller', 'lefty': ('axis', 1),
         'start': ('button', 14), 'righttrigger': ('button', 13), 'rightx': ('axis', 3),
         'x': ('button', 1), 'dpdown': ('button', 9), 'dpleft': ('button', 10),
         'back': None, 'dpup': ('button', 8), 'righty': ('axis', 4), 'a': ('button', 0),
         'b': ('button', 3), 'leftx': ('axis', 0), 'rightstick': ('button', 7),
         'leftstick': ('button', 6), 'rightshoulder': ('button', 5),
         'guid': '36280100000000000000504944564944'},
        {'lefttrigger': ('button', 5), 'leftshoulder': ('button', 4),
         'dpright': ('hat0', 2), 'platform': 'Windows', 'y': ('button', 3),
         'guide': ('button', 8), 'name': 'Thrustmaster Firestorm Dual Power',
         'lefty': ('axis', 1), 'start': ('button', 10), 'righttrigger': ('button', 7),
         'rightx': ('axis', 2), 'x': ('button', 1), 'dpdown': ('hat0', 4),
         'dpleft': ('hat0', 8), 'back': ('button', 9), 'dpup': ('hat0', 1),
         'righty': ('axis', 3), 'a': ('button', 0), 'b': ('button', 2),
         'leftx': ('axis', 0), 'rightstick': ('button', 12),
         'leftstick': ('button', 11),
         'rightshoulder': ('button', 6), 'guid': '4f0400b3000000000000504944564944'},
        {'lefttrigger': None, 'leftshoulder': ('button', 6), 'dpright': None,
         'platform': 'Windows', 'y': ('button', 4), 'guide': None,
         'name': 'RetroUSB.com RetroPad', 'lefty': ('axis', 1), 'start': ('button', 3),
         'righttrigger': None, 'rightx': None, 'x': ('button', 0), 'dpdown': None,
         'dpleft': None, 'back': ('button', 2), 'dpup': None, 'righty': None,
         'a': ('button', 1), 'b': ('button', 5), 'leftx': ('axis', 0),
         'rightstick': None,
         'leftstick': None, 'rightshoulder': ('button', 7),
         'guid': '00f00300000000000000504944564944'},
        {'lefttrigger': None, 'leftshoulder': ('button', 6), 'dpright': None,
         'platform': 'Windows', 'y': ('button', 4), 'guide': None,
         'name': 'RetroUSB.com Super RetroPort', 'lefty': ('axis', 1),
         'start': ('button', 3), 'righttrigger': None, 'rightx': None,
         'x': ('button', 0),
         'dpdown': None, 'dpleft': None, 'back': ('button', 2), 'dpup': None,
         'righty': None, 'a': ('button', 1), 'b': ('button', 5), 'leftx': ('axis', 0),
         'rightstick': None, 'leftstick': None, 'rightshoulder': ('button', 7),
         'guid': '00f0f100000000000000504944564944'},
        {'lefttrigger': ('button', 6), 'leftshoulder': ('button', 4), 'dpright': None,
         'platform': 'Windows', 'y': ('button', 3), 'guide': None,
         'name': 'GamePad Pro USB', 'lefty': ('axis', 1), 'start': ('button', 9),
         'righttrigger': ('button', 7), 'rightx': None, 'x': ('button', 0),
         'dpdown': None,
         'dpleft': None, 'back': ('button', 8), 'dpup': None, 'righty': None,
         'a': ('button', 1), 'b': ('button', 2), 'leftx': ('axis', 0),
         'rightstick': None,
         'leftstick': None, 'rightshoulder': ('button', 5),
         'guid': '28040140000000000000504944564944'},
        {'lefttrigger': ('button', 8), 'leftshoulder': ('button', 6),
         'dpright': ('hat0', 2), 'platform': 'Windows', 'y': ('button', 1),
         'guide': None,
         'name': 'SVEN X-PAD', 'lefty': ('axis', 1), 'start': ('button', 5),
         'righttrigger': ('button', 9), 'rightx': ('axis', 2), 'x': ('button', 0),
         'dpdown': ('hat0', 4), 'dpleft': ('hat0', 8), 'back': ('button', 4),
         'dpup': ('hat0', 1), 'righty': ('axis', 4), 'a': ('button', 2),
         'b': ('button', 3),
         'leftx': ('axis', 0), 'rightstick': None, 'leftstick': None,
         'rightshoulder': ('button', 7), 'guid': 'ff113133000000000000504944564944'},
        {'lefttrigger': ('button', 4), 'leftshoulder': ('button', 6),
         'dpright': ('hat0', 2), 'platform': 'Windows', 'y': ('button', 0),
         'guide': None,
         'name': 'Piranha xtreme', 'lefty': ('axis', 1), 'start': ('button', 9),
         'righttrigger': ('button', 5), 'rightx': ('axis', 3), 'x': ('button', 3),
         'dpdown': ('hat0', 4), 'dpleft': ('hat0', 8), 'back': ('button', 8),
         'dpup': ('hat0', 1), 'righty': ('axis', 2), 'a': ('button', 2),
         'b': ('button', 1),
         'leftx': ('axis', 0), 'rightstick': ('button', 11),
         'leftstick': ('button', 10),
         'rightshoulder': ('button', 7), 'guid': '8f0e0300000000000000504944564944'},
        {'lefttrigger': ('button', 6), 'leftshoulder': ('button', 4),
         'dpright': ('hat0', 2), 'platform': 'Windows', 'y': ('button', 3),
         'guide': None,
         'name': 'Multilaser JS071 USB', 'lefty': ('axis', 1), 'start': ('button', 9),
         'righttrigger': ('button', 7), 'rightx': ('axis', 2), 'x': ('button', 0),
         'dpdown': ('hat0', 4), 'dpleft': ('hat0', 8), 'back': ('button', 8),
         'dpup': ('hat0', 1), 'righty': ('axis', 3), 'a': ('button', 1),
         'b': ('button', 2),
         'leftx': ('axis', 0), 'rightstick': ('button', 11),
         'leftstick': ('button', 10),
         'rightshoulder': ('button', 5), 'guid': '8f0e0d31000000000000504944564944'},
        {'lefttrigger': ('button', 4), 'leftshoulder': ('button', 6),
         'dpright': ('hat0', 2), 'platform': 'Windows', 'y': ('button', 0),
         'guide': None,
         'name': 'PS2 USB', 'lefty': ('axis', 1), 'start': ('button', 9),
         'righttrigger': ('button', 5), 'rightx': ('axis', 4), 'x': ('button', 3),
         'dpdown': ('hat0', 4), 'dpleft': ('hat0', 8), 'back': ('button', 8),
         'dpup': ('hat0', 1), 'righty': ('axis', 2), 'a': ('button', 2),
         'b': ('button', 1),
         'leftx': ('axis', 0), 'rightstick': ('button', 11),
         'leftstick': ('button', 10),
         'rightshoulder': ('button', 7), 'guid': '10080300000000000000504944564944'},
        {'lefttrigger': ('button', 6), 'leftshoulder': ('button', 4),
         'dpright': ('hat0', 2), 'platform': 'Windows', 'y': ('button', 0),
         'guide': None,
         'name': 'G-Shark GS-GP702', 'lefty': ('axis', 1), 'start': ('button', 9),
         'righttrigger': ('button', 7), 'rightx': ('axis', 2), 'x': ('button', 3),
         'dpdown': ('hat0', 4), 'dpleft': ('hat0', 8), 'back': ('button', 8),
         'dpup': ('hat0', 1), 'righty': ('axis', 4), 'a': ('button', 2),
         'b': ('button', 1),
         'leftx': ('axis', 0), 'rightstick': ('button', 11),
         'leftstick': ('button', 10),
         'rightshoulder': ('button', 5), 'guid': '79000600000000000000504944564944'},
        {'lefttrigger': ('button', 6), 'leftshoulder': ('axis', 3),
         'dpright': ('hat0', 2),
         'platform': 'Windows', 'y': ('button', 3), 'guide': ('button', 10),
         'name': 'NYKO AIRFLO', 'lefty': ('hat0', 12), 'start': ('button', 9),
         'righttrigger': ('button', 7), 'rightx': ('hat0', 9), 'x': ('button', 2),
         'dpdown': ('hat0', 0), 'dpleft': ('hat0', 8), 'back': ('button', 8),
         'dpup': ('hat0', 1), 'righty': ('hat0', 4), 'a': ('button', 0),
         'b': ('button', 1),
         'leftx': ('hat0', 6), 'rightstick': ('axis', 2), 'leftstick': ('axis', 0),
         'rightshoulder': ('button', 5), 'guid': '4b12014d000000000000504944564944'},
        {'lefttrigger': ('button', 6), 'leftshoulder': ('button', 4),
         'dpright': ('hat0', 2), 'platform': 'Windows', 'y': ('button', 3),
         'guide': ('button', 12), 'name': 'PowerA Pro Ex', 'lefty': ('axis', 1),
         'start': ('button', 9), 'righttrigger': ('button', 7), 'rightx': ('axis', 2),
         'x': ('button', 0), 'dpdown': ('hat0', 0), 'dpleft': ('hat0', 8),
         'back': ('button', 8), 'dpup': ('hat0', 1), 'righty': ('axis', 3),
         'a': ('button', 1), 'b': ('button', 2), 'leftx': ('axis', 0),
         'rightstick': ('button', 11), 'leftstick': ('button', 10),
         'rightshoulder': ('button', 5), 'guid': 'd6206dca000000000000504944564944'},
        {'lefttrigger': None, 'leftshoulder': ('button', 6), 'dpright': ('hat0', 2),
         'platform': 'Windows', 'y': ('button', 1), 'guide': ('button', 10),
         'name': 'Saitek P2500', 'lefty': ('axis', 1), 'start': ('button', 4),
         'righttrigger': None, 'rightx': ('axis', 2), 'x': ('button', 0),
         'dpdown': ('hat0', 4), 'dpleft': ('hat0', 8), 'back': ('button', 5),
         'dpup': ('hat0', 1), 'righty': ('axis', 3), 'a': ('button', 2),
         'b': ('button', 3),
         'leftx': ('axis', 0), 'rightstick': ('button', 9), 'leftstick': ('button', 8),
         'rightshoulder': ('button', 7), 'guid': 'a3060cff000000000000504944564944'},
        {'lefttrigger': ('button', 5), 'leftshoulder': ('button', 4),
         'dpright': ('hat0', 2), 'platform': 'Windows', 'y': ('button', 3),
         'guide': None,
         'name': 'Thrustmaster Dual Analog 3.2', 'lefty': ('axis', 1),
         'start': ('button', 9), 'righttrigger': ('button', 7), 'rightx': ('axis', 2),
         'x': ('button', 1), 'dpdown': ('hat0', 4), 'dpleft': ('hat0', 8),
         'back': ('button', 8), 'dpup': ('hat0', 1), 'righty': ('axis', 3),
         'a': ('button', 0), 'b': ('button', 2), 'leftx': ('axis', 0),
         'rightstick': ('button', 11), 'leftstick': ('button', 10),
         'rightshoulder': ('button', 6), 'guid': '4f0415b3000000000000504944564944'},
        {'lefttrigger': ('button', 6), 'leftshoulder': ('button', 4),
         'dpright': ('hat0', 2), 'platform': 'Windows', 'y': ('button', 3),
         'guide': ('button', 12), 'name': 'Rock Candy Gamepad for PS3',
         'lefty': ('axis', 1), 'start': ('button', 9), 'righttrigger': ('button', 7),
         'rightx': ('axis', 2), 'x': ('button', 0), 'dpdown': ('hat0', 4),
         'dpleft': ('hat0', 8), 'back': ('button', 8), 'dpup': ('hat0', 1),
         'righty': ('axis', 3), 'a': ('button', 1), 'b': ('button', 2),
         'leftx': ('axis', 0), 'rightstick': ('button', 11),
         'leftstick': ('button', 10),
         'rightshoulder': ('button', 5), 'guid': '6f0e1e01000000000000504944564944'},
        {'lefttrigger': None, 'leftshoulder': ('button', 4), 'dpright': None,
         'platform': 'Windows', 'y': ('button', 2), 'guide': None,
         'name': 'iBuffalo USB 2-axis 8-button Gamepad', 'lefty': ('axis', 1),
         'start': ('button', 7), 'righttrigger': None, 'rightx': None,
         'x': ('button', 3),
         'dpdown': None, 'dpleft': None, 'back': ('button', 6), 'dpup': None,
         'righty': None, 'a': ('button', 1), 'b': ('button', 0), 'leftx': ('axis', 0),
         'rightstick': None, 'leftstick': None, 'rightshoulder': ('button', 5),
         'guid': '83056020000000000000504944564944'}]
elif compat_platform.startswith("darwin"):
    mapping_list = [
        {'dpright': ('hat0', 2), 'platform': 'Mac OS X', 'y': ('button', 3), 'guide': None,
         'name': 'GameStop Gamepad', 'lefty': ('axis', 1), 'start': ('button', 9),
         'righttrigger': ('button', 7), 'rightx': ('axis', 2), 'x': ('button', 2),
         'dpdown': ('hat0', 4), 'dpleft': ('hat0', 8), 'back': ('button', 8),
         'dpup': ('hat0', 1), 'righty': ('axis', 3), 'a': ('button', 0), 'b': ('button', 1),
         'leftx': ('axis', 0), 'rightstick': ('button', 11), 'leftstick': ('button', 10),
         'rightshoulder': ('button', 5), 'guid': '0500000047532047616d657061640000'},
        {'lefttrigger': ('button', 6), 'leftshoulder': ('button', 4),
         'dpright': ('hat0', 2), 'platform': 'Mac OS X', 'y': ('button', 3), 'guide': None,
         'name': 'Logitech F310 Gamepad (DInput)', 'lefty': ('axis', 1),
         'start': ('button', 9), 'righttrigger': ('button', 7), 'rightx': ('axis', 2),
         'x': ('button', 0), 'dpdown': ('hat0', 4), 'dpleft': ('hat0', 8),
         'back': ('button', 8), 'dpup': ('hat0', 1), 'righty': ('axis', 3),
         'a': ('button', 1), 'b': ('button', 2), 'leftx': ('axis', 0),
         'rightstick': ('button', 11), 'leftstick': ('button', 10),
         'rightshoulder': ('button', 5), 'guid': '6d0400000000000016c2000000000000'},
        {'lefttrigger': ('button', 6), 'leftshoulder': ('button', 4),
         'dpright': ('hat0', 2), 'platform': 'Mac OS X', 'y': ('button', 3), 'guide': None,
         'name': 'Logitech F510 Gamepad (DInput)', 'lefty': ('axis', 1),
         'start': ('button', 9), 'righttrigger': ('button', 7), 'rightx': ('axis', 2),
         'x': ('button', 0), 'dpdown': ('hat0', 4), 'dpleft': ('hat0', 8),
         'back': ('button', 8), 'dpup': ('hat0', 1), 'righty': ('axis', 3),
         'a': ('button', 1), 'b': ('button', 2), 'leftx': ('axis', 0),
         'rightstick': ('button', 11), 'leftstick': ('button', 10),
         'rightshoulder': ('button', 5), 'guid': '6d0400000000000018c2000000000000'},
        {'lefttrigger': ('axis', 2), 'leftshoulder': ('button', 4),
         'dpright': ('button', 14), 'platform': 'Mac OS X', 'y': ('button', 3),
         'guide': ('button', 10), 'name': 'Logitech F710 Gamepad (XInput)',
         'lefty': ('axis', 1), 'start': ('button', 8), 'righttrigger': ('axis', 5),
         'rightx': ('axis', 3), 'x': ('button', 2), 'dpdown': ('button', 12),
         'dpleft': ('button', 13), 'back': ('button', 9), 'dpup': ('button', 11),
         'righty': ('axis', 4), 'a': ('button', 0), 'b': ('button', 1),
         'leftx': ('axis', 0), 'rightstick': ('button', 7), 'leftstick': ('button', 6),
         'rightshoulder': ('button', 5), 'guid': '6d040000000000001fc2000000000000'},
        {'lefttrigger': ('button', 6), 'leftshoulder': ('button', 4),
         'dpright': ('hat0', 2), 'platform': 'Mac OS X', 'y': ('button', 3), 'guide': None,
         'name': 'Logitech Wireless Gamepad (DInput)', 'lefty': ('axis', 1),
         'start': ('button', 9), 'righttrigger': ('button', 7), 'rightx': ('axis', 2),
         'x': ('button', 0), 'dpdown': ('hat0', 4), 'dpleft': ('hat0', 8),
         'back': ('button', 8), 'dpup': ('hat0', 1), 'righty': ('axis', 3),
         'a': ('button', 1), 'b': ('button', 2), 'leftx': ('axis', 0),
         'rightstick': ('button', 11), 'leftstick': ('button', 10),
         'rightshoulder': ('button', 5), 'guid': '6d0400000000000019c2000000000000'},
        {'lefttrigger': ('button', 8), 'leftshoulder': ('button', 10),
         'dpright': ('button', 5), 'platform': 'Mac OS X', 'y': ('button', 12),
         'guide': ('button', 16), 'name': 'PS3 Controller', 'lefty': ('axis', 1),
         'start': ('button', 3), 'righttrigger': ('button', 9), 'rightx': ('axis', 2),
         'x': ('button', 15), 'dpdown': ('button', 6), 'dpleft': ('button', 7),
         'back': ('button', 0), 'dpup': ('button', 4), 'righty': ('axis', 3),
         'a': ('button', 14), 'b': ('button', 13), 'leftx': ('axis', 0),
         'rightstick': ('button', 2), 'leftstick': ('button', 1),
         'rightshoulder': ('button', 11), 'guid': '4c050000000000006802000000000000'},
        {'lefttrigger': ('axis', 3), 'leftshoulder': ('button', 4), 'dpright': ('hat0', 2),
         'platform': 'Mac OS X', 'y': ('button', 3), 'guide': ('button', 12),
         'name': 'PS4 Controller', 'lefty': ('axis', 1), 'start': ('button', 9),
         'righttrigger': ('axis', 4), 'rightx': ('axis', 2), 'x': ('button', 0),
         'dpdown': ('hat0', 4), 'dpleft': ('hat0', 8), 'back': ('button', 8),
         'dpup': ('hat0', 1), 'righty': ('axis', 5), 'a': ('button', 1), 'b': ('button', 2),
         'leftx': ('axis', 0), 'rightstick': ('button', 11), 'leftstick': ('button', 10),
         'rightshoulder': ('button', 5), 'guid': '4c05000000000000c405000000000000'},
        {'lefttrigger': ('axis', 2), 'leftshoulder': ('button', 4),
         'dpright': ('button', 14), 'platform': 'Mac OS X', 'y': ('button', 3),
         'guide': ('button', 10), 'name': 'X360 Controller', 'lefty': ('axis', 1),
         'start': ('button', 8), 'righttrigger': ('axis', 5), 'rightx': ('axis', 3),
         'x': ('button', 2), 'dpdown': ('button', 12), 'dpleft': ('button', 13),
         'back': ('button', 9), 'dpup': ('button', 11), 'righty': ('axis', 4),
         'a': ('button', 0), 'b': ('button', 1), 'leftx': ('axis', 0),
         'rightstick': ('button', 7), 'leftstick': ('button', 6),
         'rightshoulder': ('button', 5), 'guid': '5e040000000000008e02000000000000'},
        {'lefttrigger': ('axis', 2), 'leftshoulder': ('button', 4),
         'dpright': ('button', 14), 'platform': 'Mac OS X', 'y': ('button', 3),
         'guide': ('button', 10), 'name': 'Razer Onza Tournament', 'lefty': ('axis', 1),
         'start': ('button', 8), 'righttrigger': ('axis', 5), 'rightx': ('axis', 3),
         'x': ('button', 2), 'dpdown': ('button', 12), 'dpleft': ('button', 13),
         'back': ('button', 9), 'dpup': ('button', 11), 'righty': ('axis', 4),
         'a': ('button', 0), 'b': ('button', 1), 'leftx': ('axis', 0),
         'rightstick': ('button', 7), 'leftstick': ('button', 6),
         'rightshoulder': ('button', 5), 'guid': '891600000000000000fd000000000000'},
        {'lefttrigger': ('button', 5), 'leftshoulder': ('button', 4),
         'dpright': ('hat0', 2), 'platform': 'Mac OS X', 'y': ('button', 3),
         'guide': ('button', 8), 'name': 'Thrustmaster Firestorm Dual Power',
         'lefty': ('axis', 1), 'start': ('button', 10), 'righttrigger': ('button', 7),
         'rightx': ('axis', 2), 'x': ('button', 1), 'dpdown': ('hat0', 4),
         'dpleft': ('hat0', 8), 'back': ('button', 9), 'dpup': ('hat0', 1),
         'righty': ('axis', 3), 'a': ('button', 0), 'b': ('button', 2),
         'leftx': ('axis', 0), 'rightstick': None, 'leftstick': ('button', 11),
         'rightshoulder': ('button', 6), 'guid': '4f0400000000000000b3000000000000'},
        {'lefttrigger': ('button', 4), 'leftshoulder': ('button', 6),
         'dpright': ('hat0', 2), 'platform': 'Mac OS X', 'y': ('button', 0), 'guide': None,
         'name': 'Piranha xtreme', 'lefty': ('axis', 1), 'start': ('button', 9),
         'righttrigger': ('button', 5), 'rightx': ('axis', 3), 'x': ('button', 3),
         'dpdown': ('hat0', 4), 'dpleft': ('hat0', 8), 'back': ('button', 8),
         'dpup': ('hat0', 1), 'righty': ('axis', 2), 'a': ('button', 2), 'b': ('button', 1),
         'leftx': ('axis', 0), 'rightstick': ('button', 11), 'leftstick': ('button', 10),
         'rightshoulder': ('button', 7), 'guid': '8f0e0000000000000300000000000000'},
        {'lefttrigger': ('button', 6), 'leftshoulder': ('button', 4),
         'dpright': ('hat0', 2), 'platform': 'Mac OS X', 'y': ('button', 3),
         'guide': ('button', 12), 'name': 'HORI Gem Pad 3', 'lefty': ('axis', 1),
         'start': ('button', 9), 'righttrigger': ('button', 7), 'rightx': ('axis', 2),
         'x': ('button', 0), 'dpdown': ('hat0', 4), 'dpleft': ('hat0', 8),
         'back': ('button', 8), 'dpup': ('hat0', 1), 'righty': ('axis', 3),
         'a': ('button', 1), 'b': ('button', 2), 'leftx': ('axis', 0),
         'rightstick': ('button', 11), 'leftstick': ('button', 10),
         'rightshoulder': ('button', 5), 'guid': '0d0f0000000000004d00000000000000'},
        {'lefttrigger': ('button', 6), 'leftshoulder': ('button', 4),
         'dpright': ('hat0', 2), 'platform': 'Mac OS X', 'y': ('button', 0), 'guide': None,
         'name': 'G-Shark GP-702', 'lefty': ('axis', 1), 'start': ('button', 9),
         'righttrigger': ('button', 7), 'rightx': ('axis', 3), 'x': ('button', 3),
         'dpdown': ('hat0', 4), 'dpleft': ('hat0', 8), 'back': ('button', 8),
         'dpup': ('hat0', 1), 'righty': ('axis', 4), 'a': ('button', 2), 'b': ('button', 1),
         'leftx': ('axis', 0), 'rightstick': ('button', 11), 'leftstick': ('button', 10),
         'rightshoulder': ('button', 5), 'guid': '79000000000000000600000000000000'},
        {'lefttrigger': ('button', 5), 'leftshoulder': ('button', 4),
         'dpright': ('hat0', 2), 'platform': 'Mac OS X', 'y': ('button', 3), 'guide': None,
         'name': 'Thrustmaster Dual Analog 3.2', 'lefty': ('axis', 1),
         'start': ('button', 9), 'righttrigger': ('button', 7), 'rightx': ('axis', 2),
         'x': ('button', 1), 'dpdown': ('hat0', 4), 'dpleft': ('hat0', 8),
         'back': ('button', 8), 'dpup': ('hat0', 1), 'righty': ('axis', 3),
         'a': ('button', 0), 'b': ('button', 2), 'leftx': ('axis', 0),
         'rightstick': ('button', 11), 'leftstick': ('button', 10),
         'rightshoulder': ('button', 6), 'guid': '4f0400000000000015b3000000000000'},
        {'lefttrigger': ('axis', 2), 'leftshoulder': ('button', 4),
         'dpright': ('button', 14), 'platform': 'Mac OS X', 'y': ('button', 3),
         'guide': ('button', 10), 'name': 'Gamestop BB-070 X360 Controller',
         'lefty': ('axis', 1), 'start': ('button', 8), 'righttrigger': ('axis', 5),
         'rightx': ('axis', 3), 'x': ('button', 2), 'dpdown': ('button', 12),
         'dpleft': ('button', 13), 'back': ('button', 9), 'dpup': ('button', 11),
         'righty': ('axis', 4), 'a': ('button', 0), 'b': ('button', 1),
         'leftx': ('axis', 0), 'rightstick': ('button', 7), 'leftstick': ('button', 6),
         'rightshoulder': ('button', 5), 'guid': 'AD1B00000000000001F9000000000000'},
        {'lefttrigger': ('button', 12), 'leftshoulder': ('button', 11),
         'dpright': ('button', 1), 'platform': 'Mac OS X', 'y': ('button', 9),
         'guide': ('button', 8), 'name': 'Wii Remote', 'lefty': ('axis', 1),
         'start': ('button', 6), 'righttrigger': None, 'rightx': None, 'x': ('button', 10),
         'dpdown': ('button', 3), 'dpleft': ('button', 0), 'back': ('button', 7),
         'dpup': ('button', 2), 'righty': None, 'a': ('button', 4), 'b': ('button', 5),
         'leftx': ('axis', 0), 'rightstick': None, 'leftstick': None, 'rightshoulder': None,
         'guid': '050000005769696d6f74652028303000'}]
